@startsalt
{
{T
+Activate
++Goal
+++The game system will turn on
++Entry Conditions
+++The player presses the green activation button
++Scenario
+++The user presses green start button to begin game
++Exceptions
+++No exceptions. The game system must activate in order for the game to commence
++Exit Conditions
+++Successful Exit Conditions
++++The game begins
+++Failure to Exit Conditions
++++None
}
{T
+Play Pattern
++Goal
+++The game system will play sound pattern
++Entry Conditions
+++The player must activate the system
+++The player must continue to answer correctly
++Scenario
+++The player activates the game
+++The player answers correctly
++Exceptions
+++The player may answer incorrectly
+++The player deactivates the game before the sound is played
++Exit Conditions
+++Successful Exit Conditions
++++The system plays pattern
+++Failure to Exit Conditions
++++The player deactivates the game before the sound is played
}
{T
+Alert Wrong
++Goal
+++The game system will play a sound alerting the player they are wrong
++Entry Conditions
+++The player must activate the system
+++The player answers incorrectly
++Scenario
+++The player answers incorrectly
++Exceptions
+++The player may answer correctly
+++The player deactivates the game before the sound is played
++Exit Conditions
+++Successful Exit Conditions
++++The system alerts the player they are wrong with special tone
+++Failure to Exit Conditions
++++The player deactivates the game before the sound is played
}
{T
+Restart
++Goal
+++The game will start over
++Entry Conditions
+++The player has lost a previous round
++Scenario
+++The game automatically restarts after a player looses
++Exceptions
+++The player may decide to not play again and quit before restart
++Exit Conditions
+++Successful Exit Conditions
++++The game begins again
+++Failure to Exit Conditions
++++None
}
{T
+Activate Device
++Goal
+++Begin the game and signal the device to begin sounds
++Entry Conditions
+++None
++Scenario
+++The user presses green start button to begin game
++Exceptions
+++No exceptions. The button must be pressed to begin the game
++Exit Conditions
+++Successful Exit Conditions
++++The game begins
+++Failure to Exit Conditions
++++None
}
{T
+Deactivate Device
++Goal
+++Turn off device
++Entry Conditions
+++The device must be turned on
++Scenario
+++The user presses green button to deactivate device
++Exceptions
+++None
++Exit Conditions
+++Successful Exit Conditions
++++The device shuts down
+++Failure to Exit Conditions
++++None
}
{T
+Press Red
++Goal
+++To select the correct tone and color
++Entry Conditions
+++The user must have activated the device
+++The device must have responded to activation with a pattern
++Scenario
+++Red is the only button in the pattern.
+++Red is the first button in the pattern.
+++Red is the last button in the pattern.
+++Red is neither the first or last button but is in the pattern.
+++Red is not in the pattern.
++Exceptions
+++Red is not in the pattern
+++Red is in the pattern, but the user forgets to select it++Exit Conditions
+++Successful Exit Conditions
++++The user chooses red appropriately, and the game continues to the next pattern or ends.
+++Failure to Exit Conditions
++++The user chooses red inappropriately, and the game ends or begins again.
}
{T
+Press Green
++Goal
+++To select the correct tone and color
++Entry Conditions
+++The user must have activated the device
+++The device must have responded to activation with a pattern
++Scenario
+++Green is the only button in the pattern.
+++Green is the first button in the pattern.
+++Green is the last button in the pattern.
+++Green is neither the first or last button but is in the pattern.
+++Green is not in the pattern.
++Exceptions
+++Green is not in the pattern
+++Green is in the pattern, but the user forgets to select it
++Exit Conditions
+++Successful Exit Conditions
++++The user chooses green appropriately, and the game continues to the next pattern or ends.
+++Failure to Exit Conditions
++++The user chooses green inappropriately, and the game ends or begins again.
}
{T
+Press Yellow
++Goal
+++To select the correct tone and color
++Entry Conditions
+++The user must have activated the device
+++The device must have responded to activation with a pattern
++Scenario
+++Yellow is the only button in the pattern.
+++Yellow is the first button in the pattern.
+++Yellow is the last button in the pattern.
+++Yellow is neither the first or last button but is in the pattern.
+++Yellow is not in the pattern.
++Exceptions
+++Yellow is not in the pattern
+++Yellow is in the pattern, but the user forgets to select it
++Exit Conditions
+++Successful Exit Conditions
++++The user chooses yellow appropriately, and the game continues to the next pattern or ends.
+++Failure to Exit Conditions
++++The user chooses yellow inappropriately, and the game ends or begins again.
}
{T
+Press Blue
++Goal
+++To select the correct tone and color
++Entry Conditions
+++The user must have activated the device
+++The device must have responded to activation with a pattern
++Scenario
+++Blue is the only button in the pattern.
+++Blue is the first button in the pattern.
+++Blue is the last button in the pattern.
+++Blue is neither the first or last button but is in the pattern.
+++Blue is not in the pattern.
++Exceptions
+++Blue is not in the pattern
+++Blue is in the pattern, but the user forgets to select it
++Exit Conditions
+++Successful Exit Conditions
++++The user chooses blue appropriately, and the game continues to the next pattern or ends.
+++Failure to Exit Conditions
++++The user chooses blue inappropriately, and the game ends or begins again.
}
}
@endsalt